export function dataEmpresa() {
  const data = {
    empresa: {
      OPTICENTRO: [
        'SUCRE  CENTRAL',
        'OPTICENTRO POTOSI',
        'OPTICENTRO TUPIZA',
        'OPTICENTRO LA PAZ',
        'OPTICENTRO TARIJA',
        'OPTICENTRO YACUIBA',
        'OPTICENTRO AZURDUY',
        'OPTICENTRO TARIJA 2',
        'OPTICENTRO LA PAZ 2',
        'OPTICENTRO PARAGUAY',
        'OPTICENTRO SANTA CRUZ',
      ],
      ECONOVISION: [
        'ECONOPTICA CENTRAL',
        'ECONOPTICA PLAZA',
        'ECONOPTICA CAMPESINO',
        'ECONOPTICA POTOSI',
        'ECONOPTICA CAMARGO',
        'ECONOPTICA MORRO',
        'ECONOPTICA POTOSI 2',
        'ECONOPTICA MONTEAGUDO',
        'ECONOPTICA MEDICINA',
        'ECONOPTICA  CAMARGO CINTI',
        'ECONOPTICA TARIJA',
        'ECONOPTICA SANTA CRUZ INDANA',
        'ECONOPTICA 2 SC KOLPING',
        'ECONOPTICA EL ALTO',
        'ECONOPTICA VILLAZON',
      ],
      'TU OPTICA': ['TU OPTICA', 'TU OPTICA 2'],
      'OPTISERVICE S.R.L': ['OFEROPTICA'],
      //'ZONA OPTICA': ['ZONA OPTICA 1'],
      //'OPTILAB': ['OPTILAB', 'OPTILAB TARIJA','OPTILAB PARAGUAY'],
    },
  };
  return data;
}
